SYNTHESIA_SIGN_API_URL = 'https://hiring.api.synthesia.io'
AUTH_TOKEN = 'fc09887fe5e60c5a5efcda2e4a07ff7d'

# Cache
CACHE_CAPACITY = 1000
REDIS_HOST = 'cache'
REDIS_PORT = 6379
REDIS_PASSWORD = 'eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81'
REDIS_FIELD = 'messages'

# Evaluator
NUMBER_OF_HITS_PER_MINUTE = 10
SECONDS_TILL_NEXT_REQUEST_ATTEMPT = 60
SECONDS_BETWEEN_ATTEMPTS = 10
SECONDS_FOR_HITS_COUNTER_REFRESH = 60
